# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [ ]:
'''
前者只有第一層轉換為list，list中的每個元素仍是ndarray
後者則是將每個維度的ndarray，完全轉換為list
'''

'\n前者只有第一層轉換為list，list中的每個元素仍是ndarray\n後者則是將每個維度的ndarray，完全轉換為list\n'

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件
import numpy as np


In [ ]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))
'''
a的維度是1
a一維大小是6
a的大小是6個
a元素的資料型態是int64
a元素佔8個byte
a長度是6
a資料型態是numpy.ndarray
'''

[7 7 3 9 2 8]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


'\na的維度是1\na一維大小是6\na的大小是6個\na元素的資料型態是int64\na元素佔8個byte\na長度是6\na資料型態是numpy.ndarray\n'

In [ ]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
'''
b的維度是2
b的維度大小是3*4
b的大小是12個
b元素的資料型態是int64
b元素佔8個byte
b長度是3
b資料型態是numpy.ndarray
'''

[[4 4 7 2]
 [5 9 1 8]
 [9 5 7 1]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


'\nb的維度是2\nb的維度大小是3*4\nb的大小是12個\nb元素的資料型態是int64\nb元素佔8個byte\nb長度是3\nb資料型態是numpy.ndarray\n'

In [ ]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))
'''
c的維度是3
c的維度大小是2*3*2
c的大小是12個
c元素的資料型態是int64
c元素佔8個byte
c長度是2
c資料型態是numpy.ndarray
'''

[[[6 6]
  [4 5]
  [4 3]]

 [[6 5]
  [3 3]
  [4 0]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


'\nc的維度是3\nc的維度大小是2*3*2\nc的大小是12個\nc元素的資料型態是int64\nc元素佔8個byte\nc長度是2\nc資料型態是numpy.ndarray\n'

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print([list(i) for i in b])


[[0, 5, 1, 8], [9, 2, 2, 0], [5, 9, 3, 3]]
[[0, 5, 1, 8], [9, 2, 2, 0], [5, 9, 3, 3]]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print([[list(j) for j in i] for i in c])


[[[9, 9], [0, 0], [1, 0]], [[8, 8], [2, 0], [8, 4]]]
[[[9, 9], [0, 0], [1, 0]], [[8, 8], [2, 0], [8, 4]]]


In [ ]:
def tolist(na):
    if na.ndim == 1:
        return list(na)
    else:
        return [tolist(i) for i in na]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[1, 7, 7, 2, 7, 9]
[[0, 5, 1, 8], [9, 2, 2, 0], [5, 9, 3, 3]]
[[[9, 9], [0, 0], [1, 0]], [[8, 8], [2, 0], [8, 4]]]
