# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
import numpy as np

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


np.zeros((2, 3)) 會產生真正為 0 的陣列  
np.empty((2, 3)) 則產生近似 0 的陣列  
np.empry 可用於產生一個初始值不重要的空陣列

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [ ]:
# 記得先 Import 正確的套件
import numpy as np


In [9]:
# 參考解答

a = np.random.rand(2, 3)
a = (a * 100).round()
print(a)

[[33. 72. 75.]
 [64. 43. 65.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [57]:
m = 20
n = 40

a = np.random.rand(2, 3)
a = (a * (n - m) + m).round()

print(a)

[[36. 21. 32.]
 [25. 36. 32.]]
