# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

import numpy as np

a = np.arange(11)
a[np.logical_and(a >= 3, a <= 6)] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [4]:
A = np.random.rand(3, 6)

print(A)
print(A[A > 0.5].size)

[[0.20134063 0.93336914 0.46037051 0.45471168 0.96213267 0.55940028]
 [0.60846583 0.43897194 0.11437688 0.12426513 0.51356974 0.35541492]
 [0.34893972 0.87918947 0.1715617  0.20363385 0.82787643 0.76973777]]
8
