# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



np.sum(a) 及 sum(a) 是 numpy 中陣列的函數。  
sum(a) 則是 python 的內建函數。

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:
A = np.random.random((5, 5))
A = (A - A.min()) / (A.max() - A.min())
print(A)

[[0.26181246 0.4207144  1.         0.68005317 0.51086414]
 [0.57038695 0.56477238 0.4032146  0.80217298 0.51627422]
 [0.84305256 0.43924355 0.87924281 0.81635646 0.44768827]
 [0.73804918 0.45071265 0.79440038 0.75254867 0.57749683]
 [0.         0.1215586  0.51422148 0.58487025 0.63462046]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [7]:
A = np.random.randint(0, 100, 10)
print(A)
i = A.argmax()
A[i] = -1
print(A)

[59 38 67 94 15 67 36 15 61 71]
[59 38 67 -1 15 67 36 15 61 71]
